sudo: required
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=26.1.1
android:
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  components:
  - tools
  - platform-tools
  # The BuildTools version used by your project
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  # The SDK version used to compile your project
  - android-$ANDROID_API_LEVEL
  # Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API_LEVEL
before_install:
  - yes | sudo sdkmanager --licenses
before_script:
- chmod +x gradlew
script:
- ./gradlew build --stacktrace